version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: CSS_DEV
    environment:
      #todo: I need to figure out how to save passwords in a secure way, not plain text.
      #MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: CSS_DEV
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
