
-- ADDING FAMILY MEMBER USERS BELOW:
INSERT INTO USERS
(U_USERNAME, U_EMAIL, U_PASSWORD)
VALUES
    ('TCAHILL', '7CAHILLS@ATT.NET', 'TESTPW');

INSERT INTO USERS
(U_USERNAME, U_EMAIL, U_PASSWORD)
VALUES
    ('WCAHILL', 'CAHILL.WILLIAM@GMAIL.COM', 'TESTPW');

INSERT INTO USERS
(U_USERNAME, U_EMAIL, U_PASSWORD)
VALUES
    ('MCAHILL', 'CAHILL.MKAT@GMAIL.COM', 'TESTPW');

INSERT INTO USERS
(U_USERNAME, U_EMAIL, U_PASSWORD)
VALUES
    ('ECAHILL', 'E.T.CAHILL724', 'TESTPW');

INSERT INTO USERS
(U_USERNAME, U_EMAIL, U_PASSWORD)
VALUES
    ('KCAHILL', 'KM16CAHI@SIENA.EDU', 'TESTPW');

INSERT INTO USERS
(U_USERNAME, U_EMAIL, U_PASSWORD)
VALUES
    ('DCAHILL', 'DECLANCAHILL388@GMAIL.COM', 'TESTPW');

INSERT INTO USERS
(U_USERNAME, U_EMAIL, U_PASSWORD)
VALUES
    ('LCAHILL', 'CAHILL.LIAM220@GMAIL.COM', 'TESTPW');


-- ADDING SOME BASIC TEST COMPLIMENTS BELOW:
INSERT INTO COMPLIMENTS
(C_SENDER, C_RECEIVER, C_MESSAGE)
VALUES('LCAHILL', 'DCAHILL', 'KEEP UP THE GREAT WORK AT THE NYISO - YOU''RE DOING AWESOME!' );

INSERT INTO COMPLIMENTS
(C_SENDER, C_RECEIVER, C_MESSAGE)
VALUES('LCAHILL', 'DCAHILL', 'HOPE YOU ENJOY YOUR NEW APARTMENT!' );

SELECT * FROM COMPLIMENTS;
SELECT * FROM USERS;
