
USE CSS_DEV;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS COMPLIMENTS;

CREATE TABLE USERS
(
    U_ID SERIAL PRIMARY KEY AUTO_INCREMENT,
    U_USERNAME VARCHAR(255) NOT NULL,
    U_EMAIL VARCHAR(255) NOT NULL,
    U_PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE COMPLIMENTS
(
    C_ID SERIAL PRIMARY KEY AUTO_INCREMENT,
    C_SENDER VARCHAR(255) NOT NULL,
    C_RECEIVER VARCHAR(255) NOT NULL,
    C_MESSAGE VARCHAR(255) NOT NULL
);
